name: CoreDelta
main: CoreDelta\CoreDelta
api: 5.0.0
version: 1.0.0
author: DevPapo
description: Skywars plugin for PocketMine-MP API 5
load: POSTWORLD

commands:
  swcreate:
    description: "Crear una nueva arena"
    usage: "/swcreate <nombre>"
    permission: coredelta.command.create

  swdelete:
    description: "Eliminar una arena"
    usage: "/swdelete <nombre>"
    permission: coredelta.command.delete

  swjoin:
    description: "Unirse a una arena"
    usage: "/swjoin <arena>"
    permission: coredelta.command.join

  swleave:
    description: "Salir de la arena"
    usage: "/swleave"
    permission: coredelta.command.leave

  swstats:
    description: "Ver estadísticas"
    usage: "/swstats [jugador]"
    permission: coredelta.command.stats

  swtop:
    description: "Ver top jugadores"
    usage: "/swtop"
    permission: coredelta.command.top

  swlist:
    description: "Listar arenas"
    usage: "/swlist"
    permission: coredelta.command.list

  swtutorial:
    description: "Ver tutorial"
    usage: "/swtutorial <tipo>"
    permission: coredelta.command.tutorial

  swsetup:
    description: "Setup de arena"
    usage: "/swsetup <arena>"
    permission: coredelta.command.setup

permissions:
  coredelta.command.create:
    default: op
  coredelta.command.delete:
    default: op
  coredelta.command.join:
    default: true
  coredelta.command.leave:
    default: true
  coredelta.command.stats:
    default: true
  coredelta.command.top:
    default: true
  coredelta.command.list:
    default: true
  coredelta.command.tutorial:
    default: true
  coredelta.command.setup:
    default: op